<!-- Javascript files -->
<script src="js/front/jquery-2.2.4.min.js"></script>
<script src="bo/frontotstrap/js/bootstrap.min.js"></script>
<script src="js/front/jquery.superslides.min.js"></script>
<script src="js/front/jquery.mb.YTPlayer.min.js"></script>
<script src="js/front/jquery.magnific-popup.min.js"></script>
<script src="js/front/owl.carousel.min.js"></script>
<script src="js/front/jquery.simple-text-rotator.min.js"></script>
<script src="js/front/imagesloaded.pkgd.js"></script>
<script src="js/front/isotope.pkgd.min.js"></script>
<script src="js/front/packery-mode.pkgd.min.js"></script>
<script src="js/front/appear.js"></script>
<script src="js/front/jquery.easing.1.3.js"></script>
<script src="js/front/wow.min.js"></script>
<script src="js/front/jqBootstrapValidation.js"></script>
<script src="js/front/jquery.fitvids.js"></script>
<script src="js/front/jquery.parallax-1.1.3.js"></script>
<script src="js/front/smoothscroll.js"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="js/front/gmaps.js"></script>
<script src="js/front/contact.js"></script>
<script src="js/front/custom.js"></script>
